`etl_time`                         timestamp comment 'etl时间',
    `anchor_id`                        string comment '主播ID',
    `anchor_nick`                      string comment '主播昵称-IP名称',
    `ip_type_name`                     string comment 'IP类型 1-自有达人 2-自有明星 3-分销主播 4-店铺主播,5-投资主播',
    `account_id`                       string comment '账号ID',
    `platform_account_id`              string comment '账号唯一ID',
    `account_name`                     string comment '账号昵称',
    `platform_user_id`                 string comment '平台用户ID',
    `platform_order_no`                string comment '小Y订单号',
    `order_no`                         string comment '平台订单号',
    `order_from_id`                    string comment '订单来源',
    `order_from_name`                  string comment '订单来源(中文)',
    `platform_id`                      string comment '媒体平台',
    `platform_name`                    string comment '媒体平台(中文)',
    `order_created_at`                 string comment '下单时间',
    `payment_at`                       string comment '付款时间',
    `send_at`                          timestamp comment '发货时间',
    `received_at`                      timestamp comment '收货时间',
    `settlement_at`                    timestamp comment '结算时间',
    `goods_id`                         string comment '商品id',
    `yw_goods_id`                      string comment '遥望云商品id',
    `goods_name`                       string comment '商品名称',
    `gift_name`                        string comment '赠品信息/赠品名称',
    `goods_price`                      decimal(28, 4) comment '商品单价，单位元',
    `goods_num`                        int comment '商品数量',
    `goods_cost`                       decimal(28, 4) comment '商品成本_不包括补发换货情况',
    `supply_price`                     decimal(28, 4) comment '供货价,单比订单对应的供货价，和商品数量相关',
    `goods_img`                        string comment '商品图片',
    `shop_id`                          string comment '店铺ID',
    `shop_name`                        string comment '店铺名称',
    `created_at`                       string comment '创建时间',
    `updated_at`                       string comment '修改时间',
    `cate1_id`                         string comment '一级类目id',
    `cate1_name`                       string comment '一级类目名称',
    `cate2_id`                         string comment '二级类目id',
    `cate2_name`                       string comment '二级类目名称',
    `cate3_id`                         string comment '三级类目id',
    `cate3_name`                       string comment '三级类目名称',
    `cate4_id`                         string comment '四级类目id',
    `cate4_name`                       string comment '四级类目名称',
    `combo_sku_id`                     string comment '组合sku编码',
    `sku_name`                         string comment 'sku名称',
    `ship_sku_id`                      string comment '商家sku编码,来自于erp_order_goods_new,发货sku_id',
    `ship_sku_name`                    string comment '商品名称，来自于erp_order_goods_new,发货sku_name',
    `warehouse_name`                   string comment '仓库名称',
    `sale_user_nick`                   string comment '销售昵称',
    `platform_rate`                    decimal(18, 4) comment '渠道扣点',
    `platform_fee`                     decimal(18, 4) comment '渠道扣费,单位元',
    `business_no`                      string comment '业务类型',
    `commission_rate`                  decimal(18, 4) comment '佣金比例',
    `payment_estimated_income`         decimal(28, 4) comment '预估佣金,单位元',
    `settlement_estimated_income`      decimal(28, 4) comment '实际佣金,单位元',
    `res_commission`                   decimal(28, 4) comment '结果佣金,单位元',
    `platform_service_fee`             decimal(28, 4) comment '平台服务费,单位元',
    `tec_service_total`                decimal(28, 4) comment '技术服务费总计,单位元',
    `actual_cos_price`                 decimal(28, 4) comment '实际计算佣金金额,单位元',
    `gift_num`                         int comment '赠品数量',
    `goods_amt`                        decimal(28, 4) comment '商品单价，单位元',
    `price_rate`                       decimal(28, 4) comment '该商品的价格占比',
    `deal_amt`                         decimal(28, 4) comment '该商品的成交总价，单位元',
    `brand_id`                         string comment '品牌ID',
    `brand_name`                       string comment '品牌名称',
    `supplier_name`                    string comment '供应商名称',
    `purchaser_id`                     string comment '采销负责人ID',
    `purchaser_name`                   string comment '采销负责人名称',
    `purchaser_bu_id`                  string comment '招商对应的BU_id',
    `purchaser_bu_name`                string comment '招商对应的BU_Name',

    `supplier_id`                      string comment '供应商编号',
    `pk_id`                            string comment 'order_goods里面的pk_id',
    `order_status`                     string comment '订单状态',
    `order_status_name`                string comment '订单状态名称，如 已失效 已付款',
    `platform_category_code_route`     string comment '三方平台类目编码路径',
    `platform_category_name_route`     string comment '三方平台类目名称路径',
    `platform_cate1_id`                string comment '三方平台一级类目编码',
    `platform_cate1_name`              string comment '三方平台一级类目名称',
    `platform_cate2_id`                string comment '三方平台二级类目编码',
    `platform_cate2_name`              string comment '三方平台二级类目名称',
    `platform_cate3_id`                string comment '三方平台三级类目编码',
    `platform_cate3_name`              string comment '三方平台三级类目名称',
    `platform_cate4_id`                string comment '三方平台四级类目编码',
    `platform_cate4_name`              string comment '三方平台四级类目名称',
    `is_supplement`                    string comment '是否为补录商品',
    `is_colonel`                       string comment '是否团长订单',
    `colonel_commission_rate`          decimal(18, 4) comment '团长佣金比例',
    `activity_id`                      string comment '团长活动id',
    `colonel_estimated_commission`     decimal(18, 4) comment '团长预估佣金',
    `colonel_real_commission`          decimal(18, 4) comment '团长结算佣金',
    `colonel_tech_service_fee`         decimal(18, 4) comment '团长预估技术服务费',
    `colonel_settled_tech_service_fee` decimal(18, 4) comment '团长结算技术服务费',
    `pit_fee`                          decimal(28, 4) comment '坑位费',
    `commission_rate_offline`          decimal(18, 4) comment '线下佣金比例-提报=新提报线下佣金+保比佣金',
    `commission_rate_offline_new`      decimal(18, 4) comment '线下佣金比例-提报-新提报线下佣金',
    `commission_rate_online`           decimal(18, 4) comment '线上佣金比例-提报',
    `guarantee_commission_rate`        decimal(18, 4) comment '保比佣金比例',
    `vc_type`                          string comment '合作模式ID',
    `vc_type_name`                     string comment '合作模式名称',
    `room_id`                          string comment '合并后房间号',
    `stream_room_id`                   string comment '直播间流id',
    `stream_start_time`                timestamp comment '流开播时间',
    `stream_end_time`                  timestamp comment '流下播时间',
    `live_start_time`                  timestamp comment '合并后直播开始时间',
    `live_end_time`                    timestamp comment '合并后直播结束时间',
    `flow_source_id`                   string comment '流量来源ID，11：橱窗，12：短视频，13：直播，14：其他',
    `flow_source_name`                 string comment '流量来源名称,11：橱窗，12：短视频，13：直播，14：其他',
    `office_id`                        string comment '团队业务编号/工作室编号',
    `office_name`                      string comment '团队名称-实际就工作室名称,如吉更工作室（瑜大）',
    `dept_id`                          string comment '部门id',
    `dept_name`                        string comment '部门名称-如直播一部',
    `pid`                              string comment 'PID',
    `pay_type_id`                      string comment '支付类型 1 微信 2 支付宝，只有快手小店才获取该状态',
    `send_type`                        string comment '发货方式-来自erp_order_goods表',
    `cps_account_id`                   string comment 'CPS联盟账号ID',
    `margin_review_status`             string comment '毛利审核状态 0-未确认，1-已确认，2-无状态',
    `platform_delivery_status`         string comment '平台发货状态',
    `system_delivery_status`           string comment '系统发货状态',

    `rand_num`                         int comment 'random_num-(0-99)',
    `goods_label_id`                   string comment '商品标签ID',
    `goods_label_name`                 string comment '商品标签名称',
    `cargo_amt`                        decimal(28, 4) comment '货补成本',
    `flow_source_tag_id`               string comment '商品来源标签：0110-快手直播,0191-快手橱窗&短视频,0210-抖音直播,0221-抖音橱窗-直播期间,0222-抖音橱窗-非直播期间,0230-抖音短视频,0290-抖音其他',

    `settlement_biz_type`              string comment '订单业务类型 1-快分销，2-聚力计划',
    `order_channel`                    string comment '出单渠道:直播间',
    `estimated_commission`             decimal(28, 4) comment '预估佣金支出，单位分，机构和达人有绑定关系时返回',
    `real_commission`                  decimal(28, 4) comment '实际佣金支出，单位分，机构和达人有绑定关系时返回',
    `estimated_institution_commission` decimal(28, 4) comment '预估机构分成',
    `institution_commission`           decimal(28, 4) comment '机构分成',

    `purchaser_dept4_id`               string comment '招商4级部门ID',
    `purchaser_dept4_name`             string comment '招商4级部门名称',
    `purchaser_dept_id`                string comment '招商部门ID',

    `third_party_shop_id`              string comment '三方店铺Id',

    `is_jtk`                           string comment '是否京挑客',
    `jtk_order_no`                     string comment '京挑客订单号',
    `jtk_commission_rate`              decimal(28, 4) comment '京挑客-佣金比例',
    `jtk_estimate_cos_price`           decimal(28, 4) comment '京挑客-预估计佣金额',
    `jtk_estimate_fee`                 decimal(28, 4) comment '京挑客-预估佣金',
    `jtk_actual_cos_price`             decimal(28, 4) comment '京挑客-实际计佣金额',
    `jtk_actual_fee`                   decimal(28, 4) comment '京挑客-实际佣金',
    `updated_at_order`                 timestamp comment 'order_basic 更新时间',
    `live_title`                       string comment '直播间标题',

    `discount_amount`              decimal(28, 4) comment '订单优惠总金额-元',
    `shop_discount_amount`         decimal(28, 4) comment '商家优惠金额-元',
    `platform_discount_amount`     decimal(28, 4) comment '平台优惠金额-元',
    `talent_discount_amount`       decimal(28, 4) comment '主播优惠金额-元',
    `pay_discount_amount`          decimal(28, 4) comment '支付优惠金额-元',
    `redpack_discount_amount`      decimal(28, 4) comment '红包优惠金额-元',
    `only_platform_cost_amount`    decimal(28, 4) comment '仅平台实际承担优惠金额-元',
    `origin_refund_status`         string comment '平台订单原始的退款状态',
    `author_cost_amount`           decimal(28, 4) comment '达人实际承担优惠金额-元',
    `express_amount`               decimal(28, 4) comment '快递费-元',

    `is_fenxiao_order`             string comment '是否分销订单 0-否 1-是',
    `cps_flag`                     int comment '是否cps订单',
    `shop_flag`                    int comment '是否小店订单',
    `colonel_flag`                 int comment '是否团长订单',
    `seller_account_id`            string comment '主播账号',
    `seller_account_name`          string comment '主播账号名称',
    `after_sale_status`            int comment '售后状态：0-未售后 10-售后中 20-售后成功 30-售后关闭',
    `parent_order_no`              string comment '第三方父订单编号'