
create table if not exists `ods.fy_data_trends_mall_contracts_df` (
`id` bigint comment 'id', 
`contract_id` string comment '合同 ID', 
`original_contracts_id` string comment '原合同 Id', 
`contract_code` string comment '合同编码', 
`customer_id` string comment '商户 ID', 
`customer_code` string comment '商户编码', 
`customer_name` string comment '商户名称', 
`store_id` string comment '门店 ID', 
`store_code` string comment '门店编码', 
`store_name` string comment '门店名称', 
`con_start_date` string comment '合同开始日期', 
`con_end_date` string comment '合同结束日期', 
`con_stop_date` string comment '合同终止日期', 
`contracts_status` string comment '合同状态；2：已签约；3：执行中；4：已解约；5：已到期；6：已结算；7：已清算', 
`building_id` string comment '大楼 ID', 
`record_time` string comment '记录时间', 
`parent_id` string comment '父级 ID', 
`transfer_in_date` string comment ' ', 
`transfer_out_date` string comment ' ', 
`los_contracts_id` string comment '租赁合同 ID', 
`los_customer_id` string comment '租赁租户 ID', 
`los_brand_id` string comment '租赁品牌 ID', 
`brand_code` string comment '品牌编码', 
`brand_name` string comment '品牌名称', 
`brand_level` string comment '品牌级次', 
`los_store_id` string comment '租赁门店 ID', 
`los_f_company_id` string comment '租赁公司 ID', 
`f_company_name` string comment '公司名称', 
`manage_company_code` string comment '管理公司编码', 
`manage_company_name` string comment '管理公司名称', 
`biz_mode` string comment '合同类型;1:商铺 ；3：广告位；6：多种经营；7：仓库；8：写字楼；9：零星收费', 
`los_trade_relation_id` string comment '租赁业态 ID', 
`con_shop_id` string comment '商铺主键 ID', 
`shop_id` string comment '商铺 ID', 
`con_shop_code` string comment '商铺编码', 
`con_shop_name` string comment '商铺名称', 
`trade_code` string comment '业态编码', 
`trade_name` string comment '业态名称', 
`rent_area` string comment '签约面积', 
`modify_time` string comment '暂无', 
`create_time` string comment '暂无', 
`los_building_id` string comment '暂无', 
`los_floor_id` string comment '暂无', 
`shop_status` string comment '暂无', 
`floor_code` string comment '暂无', 
`floor_name` string comment '暂无', 
`shop_brand_name` string comment '暂无', 
`con_shop_unit_id` string comment '单元与商铺关系主键 ID', 
`unit_id` string comment '房屋 ID', 
`updated_at` string comment '更新时间', 
`created_at` string comment '创建时间', 
`etl_time` timestamp comment '数据采集时间' 
) comment '亿高-合同主数据接口'
partitioned by (`date_id` string)
row format delimited fields terminated by '\001' lines terminated by '\n'
stored as textfile
;


            

            

            

        
        
select `id`,
`contract_id`,
`original_contracts_id`,
`contract_code`,
`customer_id`,
`customer_code`,
`customer_name`,
`store_id`,
`store_code`,
`store_name`,
`con_start_date`,
`con_end_date`,
`con_stop_date`,
`contracts_status`,
`building_id`,
`record_time`,
`parent_id`,
`transfer_in_date`,
`transfer_out_date`,
`los_contracts_id`,
`los_customer_id`,
`los_brand_id`,
`brand_code`,
`brand_name`,
`brand_level`,
`los_store_id`,
`los_f_company_id`,
`f_company_name`,
`manage_company_code`,
`manage_company_name`,
`biz_mode`,
`los_trade_relation_id`,
`con_shop_id`,
`shop_id`,
`con_shop_code`,
`con_shop_name`,
`trade_code`,
`trade_name`,
`rent_area`,
`modify_time`,
`create_time`,
`los_building_id`,
`los_floor_id`,
`shop_status`,
`floor_code`,
`floor_name`,
`shop_brand_name`,
`con_shop_unit_id`,
`unit_id`,
`updated_at`,
`created_at`,

now() as etl_time
from data_trends_mall_contracts
;
