CREATE TABLE `transform_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `transform_order_no` varchar(32) NOT NULL COMMENT '免单订单编号',
  `u_id` varchar(32) DEFAULT NULL COMMENT '用户id',
  `customer_id` varchar(32) DEFAULT NULL COMMENT '会员id',
  `anchor_no` varchar(32) DEFAULT NULL COMMENT '主播编号',
  `anchor_name` varchar(200) DEFAULT NULL COMMENT '主播昵称',
  `order_anchor_no` varchar(32) DEFAULT NULL COMMENT '订单主播编号',
  `order_no` varchar(32) NOT NULL COMMENT '订单编号',
  `order_source` int(11) DEFAULT '1' COMMENT '订单来源：1-订单中心',
  `order_status` int(11) DEFAULT NULL COMMENT '订单状态：0-订单失效 1-订单付款 2-订单成功 3-订单结算',
  `goods_title` varchar(100) DEFAULT NULL COMMENT '商品名称',
  `cate_name` varchar(50) DEFAULT NULL COMMENT '商品类目',
  `order_created_at` datetime DEFAULT NULL COMMENT '订单创建时间',
  `receiver_address` varchar(200) DEFAULT NULL COMMENT '收货地址',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '修改时间',
  `deleted` int(1) DEFAULT '0' COMMENT '是否删除：0-否 1-是',
  `order_price` bigint(11) DEFAULT NULL COMMENT '订单金额',
  `points` int(11) DEFAULT NULL COMMENT '获得的积分值',
  `relation_no` varchar(64) DEFAULT NULL COMMENT '关联单号',
  `type` int(3) NOT NULL DEFAULT '0' COMMENT '类型：0-订单转换 1-新人抽奖',
  `award_type` int(3) DEFAULT NULL COMMENT '奖品类型：1-返现类 2-未中奖 3-实物类',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_order_no` (`order_no`, `type`),
  KEY `idx_transform_order_no` (`transform_order_no`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_relation_no` (`relation_no`, `deleted`),
  KEY `idx_created_at` (`created_at`, `deleted`, `type`),
  KEY `idx_anchor_no` (`anchor_no`, `created_at`),
  KEY `idx_updated_at` (`updated_at`),
  KEY `idx_uid_createtime` (`u_id`, `created_at`, `type`, `deleted`),
  KEY `idx_order_status` (`order_status`, `deleted`, `type`, `created_at`),
  KEY `idx_deleted_type_created_at` (`deleted`, `order_status`, `type`, `created_at`),
  KEY `idx_deleted_status` (`deleted`, `order_status`, `created_at`)
) ENGINE = InnoDB AUTO_INCREMENT = 5537497 DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMMENT = '转换订单表|粉丝运营|史文恭'