CREATE TABLE `data_trends_mall_contracts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `contract_id` varchar(100) DEFAULT NULL COMMENT '合同 ID',
  `original_contracts_id` varchar(100) DEFAULT NULL COMMENT '原合同 Id',
  `contract_code` varchar(100) DEFAULT NULL COMMENT '合同编码',
  `customer_id` varchar(100) DEFAULT NULL COMMENT '商户 ID',
  `customer_code` varchar(100) DEFAULT NULL COMMENT '商户编码',
  `customer_name` varchar(100) DEFAULT NULL COMMENT '商户名称',
  `store_id` varchar(100) DEFAULT NULL COMMENT '门店 ID',
  `store_code` varchar(100) DEFAULT NULL COMMENT '门店编码',
  `store_name` varchar(100) DEFAULT NULL COMMENT '门店名称',
  `con_start_date` varchar(100) DEFAULT NULL COMMENT '合同开始日期',
  `con_end_date` varchar(100) DEFAULT NULL COMMENT '合同结束日期',
  `con_stop_date` varchar(100) DEFAULT NULL COMMENT '合同终止日期',
  `contracts_status` varchar(100) DEFAULT NULL COMMENT '合同状态；2：已签约；3：执行中；4：已解约；5：已到期；6：已结算；7：已清算',
  `building_id` varchar(100) DEFAULT NULL COMMENT '大楼 ID',
  `record_time` varchar(100) DEFAULT NULL COMMENT '记录时间',
  `parent_id` varchar(100) DEFAULT NULL COMMENT '父级 ID',
  `transfer_in_date` varchar(100) DEFAULT NULL COMMENT ' ',
  `transfer_out_date` varchar(100) DEFAULT NULL COMMENT ' ',
  `los_contracts_id` varchar(100) DEFAULT NULL COMMENT '租赁合同 ID',
  `los_customer_id` varchar(100) DEFAULT NULL COMMENT '租赁租户 ID',
  `los_brand_id` varchar(100) DEFAULT NULL COMMENT '租赁品牌 ID',
  `brand_code` varchar(100) DEFAULT NULL COMMENT '品牌编码',
  `brand_name` varchar(100) DEFAULT NULL COMMENT '品牌名称',
  `brand_level` varchar(100) DEFAULT NULL COMMENT '品牌级次',
  `los_store_id` varchar(100) DEFAULT NULL COMMENT '租赁门店 ID',
  `los_f_company_id` varchar(100) DEFAULT NULL COMMENT '租赁公司 ID',
  `f_company_name` varchar(100) DEFAULT NULL COMMENT '公司名称',
  `manage_company_code` varchar(100) DEFAULT NULL COMMENT '管理公司编码',
  `manage_company_name` varchar(100) DEFAULT NULL COMMENT '管理公司名称',
  `biz_mode` varchar(100) DEFAULT NULL COMMENT '合同类型;1:商铺 ；3：广告位；6：多种经营；7：仓库；8：写字楼；9：零星收费',
  `los_trade_relation_id` varchar(100) DEFAULT NULL COMMENT '租赁业态 ID',
  `con_shop_id` varchar(100) DEFAULT NULL COMMENT '商铺主键 ID',
  `shop_id` varchar(100) DEFAULT NULL COMMENT '商铺 ID',
  `con_shop_code` varchar(100) DEFAULT NULL COMMENT '商铺编码',
  `con_shop_name` varchar(100) DEFAULT NULL COMMENT '商铺名称',
  `trade_code` varchar(100) DEFAULT NULL COMMENT '业态编码',
  `trade_name` varchar(100) DEFAULT NULL COMMENT '业态名称',
  `rent_area` varchar(100) DEFAULT NULL COMMENT '签约面积',
  `modify_time` varchar(100) DEFAULT NULL COMMENT '暂无',
  `create_time` varchar(100) DEFAULT NULL COMMENT '暂无',
  `los_building_id` varchar(100) DEFAULT NULL COMMENT '暂无',
  `los_floor_id` varchar(100) DEFAULT NULL COMMENT '暂无',
  `shop_status` varchar(100) DEFAULT NULL COMMENT '暂无',
  `floor_code` varchar(100) DEFAULT NULL COMMENT '暂无',
  `floor_name` varchar(100) DEFAULT NULL COMMENT '暂无',
  `shop_brand_name` varchar(100) DEFAULT NULL COMMENT '暂无',
  `con_shop_unit_id` varchar(100) DEFAULT NULL COMMENT '单元与商铺关系主键 ID',
  `unit_id` varchar(100) DEFAULT NULL COMMENT '房屋 ID',
  `updated_at` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `created_at` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '亿高-合同主数据接口'
